import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "The Listening Sheep| Ayomide Wayne Live Poetry Event",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${playfair.variable} ${inter.className} antialiased`}
      >
<Header/>
        {children}
      </body>
    </html>
  );
}
