import { Playfair_Display,Great_Vibes, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./header";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});
const greatVibes = Great_Vibes({
  variable: "--font-greatvibes",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "The Listening Sheep| Ayomide Wayne Live Poetry Event",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${playfair.variable} ${greatVibes.variable} ${montserrat.className} antialiased`}
      >
<Header/>
        {children}
      </body>
    </html>
  );
}
